### ISSUE TITLE
Move DeviceUnlocker source files into src

### ISSUE THREAD

**Issue by rooftopsparrow** [rooftopsparrow/resource-locking#17]
We need to move the source files provided in the DeviceUnlocker folder to be moved into the src directory so that gradle can build it.

**Comment by hdemarco4** [comment]
I got it.  I'll push later.

**Comment by hdemarco4** [comment]
Every time I push a version where this is done, it's not reflected on the github side.

**Comment by rooftopsparrow** [comment]
hmm what branch are you putting that on?

**Comment by rooftopsparrow** [comment]
I think I see it one second, I'll patch it up
