### ISSUE TITLE
Ensure that Javadoc matches spec 

### ISSUE THREAD

**Issue by rooftopsparrow** [rooftopsparrow/resource-locking#24]
We need to verify that the docs we can generate from the source code match the provided javadoc specification

**Comment by hdemarco4** [comment]
We'll have to take out the 'main' method, it's only there for testing anyway.  And everyone who made changes should put themselves as authors.  That includes writing tests.  It's also saying that there is a FourBit constructor for some reason.  I'll mess with it.

**Comment by hdemarco4** [comment]
I took out the 'main' method.

**Comment by arcturas1** [comment]
Working on the javadoc now.

**Comment by arcturas1** [comment]
Javadoc should now be in compliance with spec.

1. class description: 

- added @see with link to project description
- (personal preference) provided additional text providing clarification of authorship roles. Probably overkill, but noting who did what is I think valid acknowledgement, and Dr. Paul has not marked me off for doing so in this style for past projects.

2. Constructor Summary: removed by creating private constructor which does nothing.

**Comment by rooftopsparrow** [comment]
Closed by MR
