### ISSUE TITLE
Submission

### ISSUE THREAD

**Issue by hdemarco4** [rooftopsparrow/resource-locking#28]
Did Dr. Paul say whether we each have to submit the file, or will one of us submitting do it for the whole group?

**Comment by arcturas1** [comment]
each person has to click the submit button, but it looks like it's the same submitted item, per his recent-ish email, as follows:

From: Jody Paul <noreply@gouda.msudenver.edu>
Sent: Saturday, September 16, 2017 8:45 PM
To: Jonathan Grant
Subject: CS4250 (Fall 2017): Resource-Locking Device Project - Group Submission Process
 
 All members of the student group must click the Submit button for the assignment before the group submission will be considered as submitted.I apologize for lack of clarity of the process.  --JP

**Comment by hdemarco4** [comment]
I'm not too happy about that.  What happens if one is missing?

**Comment by arcturas1** [comment]
I'd say we should email Dr. Paul and complain that n/5 of us attempted to submit, but can't reach certain groupmates to also click the button, despite multiple such attempts.

**Comment by Mojac** [comment]
It's due tonight at 11:55pm. I leave for work around ~10:40pm so I can click submit by 10:30pm  guaranteed. As long at it doesn't "reset" and have everyone click the submit button again for what ever reason then I think my submit click would be good for the group.

**Comment by rooftopsparrow** [comment]
Lets make sure its submitted way before 11:55pm 👍 Has anyone heard from @tgolnoft ?

**Comment by rooftopsparrow** [comment]
I'm adding the file that is currently in master but not submitting until #27 is closed out

**Comment by arcturas1** [comment]
erm... I'd say look at pull request #33 and then upload the new file. The current version of the class in master will not meet specifications due to its javadoc.

**Comment by rooftopsparrow** [comment]
@hdemarco4 updated the file to take into account #33.

**Comment by rooftopsparrow** [comment]
@hdemarco4 also added the group based assessment of quality mentioned in #27

**Comment by rooftopsparrow** [comment]
I have submitted my portion.

**Comment by Mojac** [comment]
I have submitted.

**Comment by hdemarco4** [comment]
I've submitted.

**Comment by tgolnoft** [comment]
Hey guys. I'm really sorry (again). I know this isn't an acceptable situation I've placed you in. I had some more insanity come up, but that is neither here nor there. If the submission didn't go through I'll take full responsibility from Dr. Paul and endorse the good work you all did.

**Comment by tgolnoft** [comment]
If, going forward, you would like to drop me from the group, I'd fully understand. So far I've done a terrible (nonexistent) job of pulling my weight, and this time it truly impacted you all beyond the dead weight. If you'd like to still have me going into the next project I promise I will do better, and will sincerely try to make it up to all of you.

Whatever decision you make, I really am sorry.

**Comment by rooftopsparrow** [comment]
Thanks for owning up to it and apologizing. 

For myself, I'm 100% ok with you continuing with the group because I think this is the the whole point of the "team building" exercise of this project. I also want to give you the benefit of the doubt because I think if something came up for any one of us, we'd want the same.

**Comment by arcturas1** [comment]
Apology wholeheartedly accepted, thank you! :)

I second Jonathan's sentiment; I bear no ill-will over the circumstances and such. My only request going forward is that if anything comes up for anyone, that we all take a moment to note that life is broken and we will need to be out fixing it. 

I Look forward to working with you on projects in class going forward ^^

**Comment by rooftopsparrow** [comment]
Closing, as this was completed.
