### ISSUE TITLE
Process Documentation

### ISSUE THREAD

**Issue by hdemarco4** [rooftopsparrow/resource-locking#34]
"Use this assignment's Online text to provide the documentation of your development and a group-based reflection addressing your insights and observations from your experiences with this assignment. The process documentation includes identifying activities and decisions in the order they occurred. It also includes an assessment of the process (how well it worked; what aspects worked well; what aspects would you change). Your group-based reflection should address aspects related to working in a group as well as other software engineering practices."

**Update**: Each person in the group should quickly draft out talking points of how to document our experience. After we compare everyone's drafts, we can create a final mush together of those drafts. We should shoot for closing this issue by Friday.

**Comment by hdemarco4** [comment]
•	Use slack for communication
•	Use github for the repository
•	Started documentation
•	Started discussing algorithm
•	Choose build tool (gradle)
•	Each gave a brief bio to build the team
•	Added Device jar to git
•	Wrote FourBit
•	Added CI to project
•	Wrote Device for testing
•	Wrote tests, made sure FourBit met spec
•	Submit

I think this is a good list of the points we need to hit.

**Comment by Mojac** [comment]
I really like that list. I think the slack and the GitHub-issues worked well and were really helpful for communication. Also, peer-reviewing code by team members before it got pushed to the repo seemed to help things fit together.

**Comment by rooftopsparrow** [comment]
I wrote this down yesterday:

- Initial Project Setup
  - Meet group
  - Agree on slack
  - Agree on Github
  - Discuss making all descisions over slack and github
- Initial descisions
  - Create issues on github for tracking things that need to get done
  - Discuss and choose build tool
  - Start writing documentation
  - Discuss designs for algorithm 
- Team building
  - we gave small biographies
  - small in person meetings after class
  - Encouraging redoing work just for learning
  - Pull Requests and peer review
- Development Work
  - Base project structure with gradle build tool
  - CI/CD with stub tests
  - Algorithm implemented
  - Device jar added
  - Tests added and implemented
  - Device Test Class implemented for more robust testing
  - javadoc to spec

**Comment by arcturas1** [comment]
* Initial in-person meeting
	* Introductions
	* Determined that future discussions would need to take place mostly online, as our group members' schedules did not permit meetings in person.
		* Chose Slack as our informal communications medium
		* Chose GitHub as our code repository
		* Chose to use an open-source-like process model to accommodate our members' schedules
	* Discussed algorithm and options for the selection thereof
* Created [Slack Channel](https://msudenver-cs4250-2017.slack.com/messages/C705U3ESJ/)
* Created [GitHub Project](https://github.com/rooftopsparrow/resource-locking)
	* Added team members as collaborators to GitHub project
	* Decided to use GitHub as our formal communications medium
	* Began implementing process model through GitHub; Process is as follows:
		* Continuous integration is used to ensure that all code is tested against the current standards prior to merge.
		* Issues are raised to answer questions, make major product decisions (such as process changes and application design decisions), and track progress on tasks necessary to implement the application design
		* Issues related to implementation tasks are assigned to team members, possibly by the assignee, to show ownership; joint ownership is possible.
		* Any discussion related to a task, such as how to implement it, should be added to that task's issue
		* A pull request is made to resolve an implementation task-issue
			* The pull request is reviewed by the team, and merged after achieving consensus
			* Merging the pull request closes the issue.
			* Changes to enhance or fix code are addressed by opening a new task-issue
* Provided short bio's to get to know one another better and build the team
* Second in-person meeting
	* Discussed build tool options: narrowed to Maven, Gradle, or Ant
	* Chose initial approach to the algorithm: brute force heuristic. Due to time constraints and having a need to have Something done, this seemed like the best option to start with. Once a working product was tested and ready to release, We could then augment or change the way that we approached the problem.
	* Decide that our project [needs more kitties](https://github.com/rooftopsparrow/resource-locking/issues/15)
* [Chose a build tool](https://github.com/rooftopsparrow/resource-locking/issues/6): Gradle
* [Keep the product goal in sight](https://github.com/rooftopsparrow/resource-locking/issues/7): add requirements doc to project
* [Added gradle as base for the project](https://github.com/rooftopsparrow/resource-locking/issues/9)
* [Added device jar to project](https://github.com/rooftopsparrow/resource-locking/issues/11)
* [Decide on format of showTrace() output](https://github.com/rooftopsparrow/resource-locking/issues/13)
* [Implemented unlock heuristic](https://github.com/rooftopsparrow/resource-locking/issues/12)
* [Add Continuous Integration to project](https://github.com/rooftopsparrow/resource-locking/issues/14)
* [Configure circleci](https://github.com/rooftopsparrow/resource-locking/pulls/19)
* [Create tests and add tracing](https://github.com/rooftopsparrow/resource-locking/pulls/23)
* [Create our own device class for more robust testing](https://github.com/rooftopsparrow/resource-locking/issues/16)
* [Decide on a future enhancement to the heuristic: also try unlocking with F](https://github.com/rooftopsparrow/resource-locking/issues/29)
* [Ensure javadoc matches spec](https://github.com/rooftopsparrow/resource-locking/issues/24)
* [Assess the quality of our product](https://github.com/rooftopsparrow/resource-locking/issues/27)
* [Submit the product](https://github.com/rooftopsparrow/resource-locking/issues/28)

**Comment by tgolnoft** [comment]
The above looks really good. It has all of the major developments in the order they came up. Should it be submitted in an outline form or prose? If we need to extend it out of the outline form I'll have some time tonight and all day tomorrow I could work on it. I could get a first draft up by early afternoon pretty easily, and barring any major changes submit the thing by early evening.

**Comment by hdemarco4** [comment]
I think the above is good.  Now we just need to say what went well, what didn't, and the group reflection.  I think it all went really well, especially peer reviewing the code.  The only thing I might change is trying to meet in person a bit more.  We knew that was going to be a problem from the beginning, though.

**Comment by arcturas1** [comment]
Well, I think in-person meetings would be great, but... we're not "just" sofware engineers, so I think that working to solve problems and be a team within real world constraints, we did as best as could be expected of ourselves on that front ^^

**Comment by rooftopsparrow** [comment]
@tgolnoft Sounds good if you want to take a stab at it.

My summary for the second half of the docs:

>  It also includes an assessment of the process (how well it worked; what aspects worked well; what aspects would you change).

I think it worked out ok. I would change the project to be smaller, like three to four person teams. Five people for this project is really tough. I'm 

Group reflection:

I actually enjoyed working on things on Github with people I just met. There were bumps but that comes with the being on a new team. I also think, given the short length of time we've worked together, and limited in-person interaction, that the team formed pretty well. The process of development kind of guided itself. Pick an issue and work on it. Slack made it easy to discuss things quickly, while Github issues gave the issues more formal docs to decisions.

**Comment by tgolnoft** [comment]
Alright, taking all of these suggestions. I think baring my personal communication issues it all went pretty well. Only thing I have to add that we maybe could have done better is that we did get a pretty late start on it and could probably have gotten the ball moving a little faster. I'm finishing up now, I'll post a draft here in probably a half hour

**Comment by arcturas1** [comment]
My apologies in advance for the poor quality of my writing in the below; I'm feeling pretty sick today, so I'm having trouble being concise. I do hope the meaning comes through well, though; please let me know if I need to clarify anything.

My assessment of the process is as follows: 
Overall, I think that our process worked very well; we delivered a good quality product. Really there isn't a part of it that I would remove, but I would like to augment it with a couple things that I think could have helped: 
1. Build in more client involvement
   * The reasoning for this is that when answering the after-project questionnaire, there were many questions about how the client would feel about the work. While I'd like to believe that I can intuit what a client wants from the initial requirements spec, I can't say with confidence that I have met their expectations without communicating with them more prior to delivering a product. **Furthermore, when we did contact Dr. Paul at the end of the assignment, he noted that he just would have liked to have had more contact from us sooner, so I think that even if the client doesn't get exactly what they wanted, if they had insight into why, and what was going on, this would make them more happy with whatever they do end up getting.**
2. Arrange some time to share screens and have a conference call of some sort
   * The reasoning for this is that I think that given the scope of the project, we were all kinda shying away from the "write the code" part because once an algorithm is chosen, it's like 30 minutes of actual coding and it's done; there just isn't so much work to go around. Pair or group programming would have worked well for it, but that presupposes that the group can get together physically. So, since we're working with an open source model where mostly people can't be physically together at length, this approach should make some sense, even if that means just 2 people getting together on the project at once, that still gives 2 credits and lets us be more collaborative vs cooperative.


As to reflection, I think that the bolded portion of the reasoning for point 1is basically reflective, and is my main takeaway thing for this project. It's not that I want to "be agile" or "use an agile model" or some such thing, but really just involving the client to whom a product with be delivered in the development of that product would give me more confidence in knowing what the client thinks about said product.

**Comment by tgolnoft** [comment]
What I have so far. Mostly first half stuff, feel free to add to it if you have suggestions or edits, otherwise we can just append a part 2 to it and submit.

[Reflections.docx](https://github.com/rooftopsparrow/resource-locking/files/1327743/Reflections.docx)

**Comment by tgolnoft** [comment]
The above, but text:

 
Initial Class Meeting:
We initially got together in class to discuss how we were going to communicate and the conventions we would use going forward. After brief introductions we realized that our schedules were going to make in-person meetings difficult, and we would need to work out remote solutions. We decided on hosting our code on GitHub as some of our members were familiar with it. For team communication Slack seemed like the best fit as most of us had used it and its team based structure was well suited for our needs. Given our schedules and the need for us to do most of the work remotely we chose a process model based on open-source development where coding is mostly done individually. As we would come across problems or need to consult with the other members we would raise an issue on GitHub. After the other members have weighed in and we had come to a consensus the issue would be closed and we would go back to our respective work. This allowed us to not only stay on the same page but also to make sure that if a member got stuck on a problem it would be quickly and easily addressable. We wrapped up the initial meeting by discussing a few ideas for the algorithm, but we did not reach a consensus at that time.
Early Stages:
Shortly after the meeting we created the Slack channel and the GitHub repository. During this time we also formalized our process model and began implementing it through GitHub. On Slack we provided short bios to help us get to know each other better and bond as team.
The process model we ended with was as follows:
•	Continuous integration is used to ensure that all code is tested against the current standards prior to merge.
•	Issues are raised to answer questions, make major product decisions (such as process changes and application design decisions), and track progress on tasks necessary to implement the application design
•	Issues related to implementation tasks are assigned to team members, possibly by the assignee, to show ownership; joint ownership is possible.
•	Any discussion related to a task, such as how to implement it, should be added to that task's issue
•	A pull request is made to resolve an implementation task-issue
•	The pull request is reviewed by the team, and merged after achieving consensus
•	Merging the pull request closes the issue.
•	Changes to enhance or fix code are addressed by opening a new task-issue
Second In-Person Meeting:
In our second class meeting we decided to solidify the big picture elements we had not figured out yet, namely the build tool we would use and our overall approach to the algorithm. We narrowed our build tool options to Maven, Gradle, or Ant and opened an issue on GitHub for discussion. For our algorithm we prioritized making progress over finding the best solution and so decided that, at least for the short term, we would go with the simple solution of a brute force algorithm.
Development Process:
The first issue addressed was our build tool. We decided on Gradle as some of our members have worked with it before. We also did some initial commits for the Gradle file, the device jar, and the requirements document. 
We next had a pair of issues opened around our specific implementation. The first one was discussing the format of the showTrace() output. It went up and was accepted very quickly, with members suggesting small tweaks to the original proposal that was ultimately accepted. The other issue was us deciding on our final algorithm. We batted around a few ideas while making sure we all understood the spec correctly. After a day of discussion, we again decided to keep it simple and stay with a brute force approach, but we did think of a few ways to possibly improve it given time as well. We also decided to integrate continuous integration into the project by way of circleci. It especially made sense given the distributed nature of our process. 
As we started splitting off to code either the unlocker or the tests to run it against we continued to discuss possible improvements to be made if we needed to or felt we had time to. As the code started coming in and passing tests we were roughly down to polishing and assessing the quality of the final product and making sure it matches the spec.

**Comment by tgolnoft** [comment]
I also think we should be frank about my (lack of) contribution and the end ramifications of that, I'm just having a bit of trouble wording it myself. It and our follow up to it was a part of the 'process,' and certainly should be addressed in our reflections, both personal and individual.

**Comment by arcturas1** [comment]
@tgolnoft, I think it's a fair point that it was part of how the product was developed, However, You were contributing insofar as how we made the decision for a particular algorithm, and offered an approach. And I see those considerations and decisions as having been more work than actually writing the code to implement it. Which is basically what we explained to Dr. Paul. Hell, if we're going to get on people about "how much did **you** contribute, then other than arguing passionately about algorithm stuff, the only material contribution I made was touching up some javadoc.

Now then, Dr. Paul had asked us "... if Travis wasn't communicating with you, why didn't you tell me about this sooner?" Our answer is that when we met in person during or after class, it seemed that you'd be there working on the project, and you contributed to our decisions and posted suggestions to how to work out a solution in the early issues. There is a tendency, in the accountability game, to want to be retributive, and assign (or take) all the blame for everything that may have been wrong. Being frank about contributions means acknowledging blame where it's due, but not overdoing it. And also giving credit where due

So, we acknowledge that life stuff came up and precluded you from contributing later in the development process. We were slow to come to initial decisions, to which you made clear contributions, and later in the process stuff came up for you. We as a team didn't communicate our processes to Dr. Paul, who may have been able to reach out to you differently, which is a blame the whole team must accept, and the one that can be dealt with via changing processes. We could, I suppose, also mandate daliy communication, but I think that "checking slack at least once a day" was one of our initially adopted standards, it just didn't get written down, so I forgot to mention it in the process breakdown. So I don't know that there's necessarily a process failure for that bit, but that communication item is really the full scope of "blame" which needs be assigned to you. However, if you'd like it directly incorporated, then here's a thing regarding how "Submit the product" can break down which does so in my view:

* [Submit the product](https://github.com/rooftopsparrow/resource-locking/issues/28)
   * Begin worring about product submission: What if a team member can't click submit?"
   * Decide that our recourse will be to contact Dr. Paul to notify him that n/5 team members were unavailable to submit the product
   * Realize fears: Travis wasn't available to submit the product
   * Begin panicking about being able to submit the product
   * Have all available members click submit button
   * Contact Dr. Paul and notify him of the submission problem

**Comment by arcturas1** [comment]
I don't know to what extent the others (dis)agree with me, but the above is how I'm looking at things, and my general views can be summed as follows: I don't really care who is to blame for a thing (retributive justice), I care that the thing gets fixed (corrective justice). And that view is what drives my take on the situation above

**Comment by arcturas1** [comment]
First stab at a document incorporating the input that we've had so far and addressing description, assessment and reflection

**Process Description:** 
* Initial Class Meeting:
	* We initially got together in class to discuss how we were going to communicate and the conventions we would use going forward. After brief introductions we realized that our schedules were going to make in-person meetings difficult, and we would need to work out remote solutions. We decided on hosting our code on GitHub as some of our members were familiar with it. For team communication Slack seemed like the best fit as most of us had used it and its team based structure was well suited for our needs. Given our schedules and the need for us to do most of the work remotely we chose a process model based on open-source development where coding is mostly done individually. As we would come across problems or need to consult with the other members we would raise an issue on GitHub. After the other members have weighed in and we had come to a consensus the issue would be closed and we would go back to our respective work. This allowed us to not only stay on the same page but also to make sure that if a member got stuck on a problem it would be quickly and easily addressable. We wrapped up the initial meeting by discussing a few ideas for the algorithm, but we did not reach a consensus at that time.
* Early Stages:
	* Shortly after the meeting we created the Slack channel and the GitHub repository. During this time we also formalized our process model and began implementing it through GitHub. On Slack we provided short bios to help us get to know each other better and bond as team. The process model we ended with was as follows:
		* Continuous integration is used to ensure that all code is tested against the current standards prior to merge.
		* Issues are raised to answer questions, make major product decisions (such as process changes and application design decisions),
		and track progress on tasks necessary to implement the application design
		* Issues related to implementation tasks are assigned to team members, possibly by the assignee, to show ownership; joint ownership is possible.
		* Any discussion related to a task, such as how to implement it, should be added to that task's issue
		* A pull request is made to resolve an implementation task-issue
			* The pull request is reviewed by the team, and merged after achieving consensus
			* Merging the pull request closes the issue.
			* Changes to enhance or fix code are addressed by opening a new task-issue
		* Each team member should check slack at least once a day to contribute to ongoing informal team discussion
* Second in-person meeting
	* In our second class meeting we decided to solidify the big picture elements we had not figured out yet, namely the build tool we would use and our overall approach to the algorithm. We narrowed our build tool options to Maven, Gradle, or Ant and opened an issue on GitHub for discussion. For our algorithm we prioritized making progress over finding the best solution and so decided that, at least for the short term, we would go with the simple solution of a brute force algorithm. 
	* We also decided that our project needs more kitties
* Development Process:
	*The first issue addressed was our build tool. We decided on Gradle as some of our members have worked with it before. We also did some initial commits for the Gradle file, the device jar, and the requirements document.
	* We next had a pair of issues opened around our specific implementation. The first one was discussing the format of the showTrace() output. It went up and was accepted very quickly, with members suggesting small tweaks to the original proposal that was ultimately accepted. The other issue was us deciding on our final algorithm. We batted around a few ideas while making sure we all understood the spec correctly. After a day of discussion, we again decided to keep it simple and stay with a brute force approach, but we did think of a few ways to possibly improve it given time as well. We also decided to integrate continuous integration into the project by way of circleci. It especially made sense given the distributed nature of our process.
	* As we started splitting off to code either the unlocker or the tests to run it against, we continued to discuss possible improvements to be made if we needed to or felt we had time to. As the code started coming in and passing tests we were roughly down to polishing and assessing the quality of the final product and making sure it matches the spec.
* Submit the product
	* On Saturday, 8/16, we began worrying about product submission: "What if a team member can't click submit?" We decided that our recourse would be to contact Dr. Paul to notify him that n/5 team members were unavailable to submit the product. On Sunday, 8/17, we realized our fear: Travis wasn't available to submit the product. We then begin panicking about being able to submit the product. All available members clicked the submit button, and then we contacted Dr. Paul to notify him of the submission problem
	
**Process Assessment:**
* How well it worked Overall: we feel that our open-source-like process worked fairly well, given the time constraints of our group. On a 	10-point scale with 10 being the highest, we give it a 7.5.
* What worked well:
	* Handling development tasks via issues on GitHub allowed us to track our progress effectively, deliver iteratively, provide constructive 		feedback, and obtain group consensus, for product changes. 
	* Our in-person meetings were very productive, and we came to decisions relatively rapidly during them
* What aspects we would change:
	* We had some issues with communication, and our process should have included more focus on encouraging better, more iterative communication 	among team members.
	* Attempting to hold ourselves to committing to more in-person meetings, or adopting a tool to share screens and hold conference calls (e.g.: 	TeamViewer, Skype, etc.) if that proved too burdensome would have improved our process.
	* We should have started work sooner, to allow more time to refine our code and further improve its quality
	* We should have added a mechanism to involve our client in our development process
		
**Reflection:**
* We found that we enjoyed working on things on GitHub with people we'd just met. There were bumps, but that comes with the being on a new team. We also think, given the short length of time we've worked together, and limited in-person interaction, that the team formed pretty well. The process of development kind of guided itself. Pick an issue and work on it. Slack made it easy to discuss things quickly, while GitHub issues gave the issues more formal documentation to accompany decisions.

**Comment by tgolnoft** [comment]
I like the above, it cleaned up what I had as well as incorporating the missing elements. Barring any objections or additions it is definitely something I'm comfortable signing my name to.

**Comment by rooftopsparrow** [comment]
This is a good submission. I'm good with this draft.

**Comment by tgolnoft** [comment]
Ok then I have submitted!

**Comment by arcturas1** [comment]
I think that makes all of us, with the submission complete, I'm closing this issue out
